name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate package.json
        run: |
          cat <<EOF > package.json
          {
            "name": "grafana-plugin",
            "version": "1.0.0",
            "description": "Grafana APM Panel",
            "main": "index.js",
            "scripts": {
              "build": "tsc"
            },
            "dependencies": {},
            "devDependencies": {
              "typescript": "^4.0.0"
            }
          }
          EOF

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build || echo "No build step defined"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

