name: Build Plugin

on:
  push:
    branches: [main]

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate package.json
        run: |
          cat <<EOF > package.json
          {
            "name": "grafana-plugin",
            "version": "1.0.0",
            "description": "Grafana APM Panel",
            "main": "index.js",
            "scripts": {
              "build": "tsc"
            },
            "dependencies": {},
            "devDependencies": {
              "typescript": "^4.0.0"
            }
          }
          EOF

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build

      - name: Verify `dist/` exists
        run: ls -lah dist/

      - name: Package plugin
        run: tar -czvf grafana_plugin.tar.gz dist/

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana-plugin
          path: grafana_plugin.tar.gz
