name: Build and Package Grafana Plugin in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:    
    runs-on: ubuntu-latest 
    steps:        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |          # ← Texto multilínea indentado
          npm install -g @grafana/toolkit
          npm install

      - name: Build plugin
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t grafana-springboot-apm .
