name: Build and Package Grafana Plugin in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies and build the plugin
      - name: Install dependencies
        run: |
          npm install -g @grafana/toolkit
          npm install
      - name: Build the plugin
        run: npm run build

      # Create a Docker image with Grafana and the plugin
      - name: Build Docker image
        run: |
          docker build -t grafana-springboot-apm .

      # Push Docker image to Docker Hub (optional)
     - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
