name: Extract Package from Docker Image

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  extract-package:
    runs-on: ubuntu-latest
    permissions:
      packages: read  # Permite leer imágenes de GitHub Container Registry

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the existing Docker image
        run: docker pull ghcr.io/jcazorla90/grafana_plugin_apm:75b185722590c93bc7de9a4e8f8e7ac624508bc7

      - name: Create a container from the image
        run: docker create --name grafana-plugin-container ghcr.io/jcazorla90/grafana_plugin_apm:75b185722590c93bc7de9a4e8f8e7ac624508bc7

      - name: Verify files in the container
        run: docker run --rm ghcr.io/jcazorla90/grafana_plugin_apm:75b185722590c93bc7de9a4e8f8e7ac624508bc7 ls -lah /package || echo "ERROR"

      - name: Extract the package from the container
        run: docker cp grafana-plugin-container:/package/grafana_plugin.tar.gz . || echo "ERROR"

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grafana-plugin
          path: grafana_plugin.tar.gz
